version: 0.2

phases:
  install:
    commands:
      - echo Installing serverless
      - npm install -g serverless
  pre_build:
    commands:
      - echo Install source NPM dependencies
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the Serverless framework
      - serverless deploy -v -s $ENV_NAME

  post_build:
    commands:
      - echo Deployment completed on `date`
